version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    container_name: postgre_db_prod_foodgram
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    container_name: backend_prod_foodgram
    image: ivenauto/foodgram_backend
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    restart: on-failure
  frontend:
    container_name: frontend_prod_foodgram
    image: ivenauto/foodgram_frontend
    env_file:
      - .env
    command: cp -r /app/build. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
    restart: no
  nginx:
    container_name: nginx_prod_foodgram
    image: nginx:1.19.3
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - /home/yc-user/foodgram/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
    restart: always
