# Generated by Django 4.2.5 on 2023-10-18 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_follow_subscriptions_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='Вы уже подписаны на этого автора',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='Нельзя подписаться на себя',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='following',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания подписки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='\nВы уже подписаны на этого автора\n'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('user')), _negated=True), name='\nНельзя подписаться на себя\n'),
        ),
    ]
