# Generated by Django 4.2.5 on 2023-10-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='\nВы уже подписаны на этого автора\n',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='\nНельзя подписаться на себя\n',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='Вы уже подписаны на этого автора'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('user')), _negated=True), name='Нельзя подписаться на себя'),
        ),
    ]
