# Generated by Django 4.2.5 on 2023-10-17 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_amountingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={'ordering': ('recipe',), 'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.RemoveConstraint(
            model_name='amountingredient',
            name='\nrecipes_amountingredient ingredient already added\n',
        ),
        migrations.RemoveConstraint(
            model_name='favorites_recipes',
            name='\nrecipes_favorites_recipes recipe is favorite alredy\n',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='\nrecipes_ingredient_name is empty\n',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='\nrecipes_ingredient_measurement_unit is empty\n',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_for_author',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='\nrecipes_recipe_name is empty\n',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='\nrecipes_shoppingcart recipe is cart alredy\n',
        ),
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не менее 1')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='favorites_recipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='recipes.recipe', verbose_name='Рецепт из избранного'),
        ),
        migrations.AlterField(
            model_name='favorites_recipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Автор избранного'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Не менее 1 мин.')], verbose_name='Время приготовления, мин'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopcarts', to='recipes.recipe', verbose_name='Рецепты из списка покупок'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopcarts', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок пользователя'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7, unique=True, verbose_name='Цвет в НЕХ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(db_index=False, max_length=200, unique=True, verbose_name='Идентификатор тэга'),
        ),
        migrations.AddConstraint(
            model_name='amountingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='recipe_ingredient_unique'),
        ),
        migrations.AddConstraint(
            model_name='favorites_recipes',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_favorite_recipes'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_cart_user_recipes'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'color', 'slug'), name='unique_tag'),
        ),
    ]
