# Generated by Django 4.2.5 on 2023-10-20 10:58

import basys.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image_recipe_unique_for_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[
                                   basys.validators.ValidateName(field='Название тэга')], verbose_name='Название'),
        ),
    ]
