# Generated by Django 4.2.5 on 2023-10-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_basket_favorite_remove_favorites_recipes_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Список покупок',
                     'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.RemoveConstraint(
            model_name='basket',
            name='\nrecipes_basket recipe is list already\n',
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='recipes_basket recipe is list already'),
        ),
    ]
