# Generated by Django 4.2.5 on 2023-10-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_basket_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='\nrecipes_ingredient_measurement_unit is empty\n',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(
                ('measurement_unit__length__gt', 0)), name='recipes_ingredient_measurement_unit is empty'),
        ),
    ]
