# Generated by Django 4.2.5 on 2023-12-16 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_author_recipe_unique_for_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(
                1, message='Не менее 1'), django.core.validators.MaxValueValidator(10000, message='Слишком много!')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(
                1, message='Не менее 1 мин.'), django.core.validators.MaxValueValidator(600, message='Более 600 мин - слишком долго')], verbose_name='Время приготовления, мин'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Описание блюда'),
        ),
    ]
