# Generated by Django 4.2.5 on 2023-09-23 12:37

import basys.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Необходимо указать. Это имя будет отображаться в системе. Максимум 150 знаков.',
                                   max_length=158, unique=True, validators=[basys.validators.ValidateName]),
        ),
    ]
