# Generated by Django 4.2.5 on 2023-09-23 12:39

import basys.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(
                help_text='Необходимо указать. Максимум 158 знаков.', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(
                help_text='Необходимо указать. Максимум 158 знаков.', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Необходимо указать. Это имя будет отображаться в системе. Максимум 158 знаков.',
                                   max_length=158, unique=True, validators=[basys.validators.validate_name]),
        ),
    ]
