# Generated by Django 4.2.5 on 2023-09-23 12:41

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(
                help_text='Необходимо указать. Максимум 150 знаков.', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(
                help_text='Необходимо указать. Максимум 150 знаков.', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Необходимо указать. Это имя будет отображаться в системе. Максимум 150 знаков.',
                                   max_length=150, unique=True, validators=[core.validators.ValidateName]),
        ),
    ]
