# Generated by Django 4.2.5 on 2023-10-17 09:33

import basys.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_follow_options_remove_follow_unique_follow_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscriptions',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с данным e-mail уже зарегестрирован.'}, help_text='Необходимо указать. Максимум 254 знаков.', max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Логин занят.'}, help_text='Необходимо указать. Это имя будет отображаться в системе. Максимум 150 знаков.', max_length=150, unique=True, validators=[basys.validators.ValidateName], verbose_name='Логин'),
        ),
    ]
