# Generated by Django 4.2.5 on 2023-10-20 10:58

import basys.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_subscriptions_вы_уже_подписаны_на_этого_автора_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Логин занят.'}, help_text='Необходимо указать. Это имя будет отображаться в системе. Максимум 150 знаков.', max_length=150, unique=True, validators=[basys.validators.ValidateName(field='Имя пользователя')], verbose_name='Логин'),
        ),
    ]
