# Generated by Django 4.2.5 on 2023-10-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_subscriptions__вы_уже_подписаны_на_этого_автора__and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активирован'),
        ),
    ]
