# Generated by Django 4.2.5 on 2023-12-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='Вы уже подписаны на этого автора',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='Нельзя подписаться на себя',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='you_are_already_subscribed_to_this_author'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('user')), _negated=True), name='impossible_subscribe_to_yourself'),
        ),
    ]
