# Generated by Django 4.2.5 on 2023-12-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_subscriptions_вы_уже_подписаны_на_этого_автора_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='You_are_already_subscribed_to_this_author',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name="You_can't_follow_yourself",
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='you_are_already_subscribed_to_this_author'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('user')), _negated=True), name="you_can't_follow_yourself"),
        ),
    ]
