# Generated by Django 4.2.5 on 2023-12-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_subscriptions_you_are_already_subscribed_to_this_author_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name="you_can't_follow_yourself",
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.CheckConstraint(check=models.Q(('author', models.F('user')), _negated=True), name='impossible_subscribe_to_yourself'),
        ),
    ]
